  version: "3"
  services: 
    api:
      image: brunafin/ecofin-api-ts
      ports:
        - "3000:3000"
      links:
        - link-db
    link-db:
      image: mongo
      ports:
        - "27017:27017"
        - "28017:28017"
      environment:
        - AUTH=no